version: '3.8'

services:
  db:
    image: postgres:14.10-alpine3.18
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: app
      POSTGRES_PASSWORD: 123123123
    ports:
      - "5432:5432"

  web:
    image: molbert:latest
    command: uvicorn app.mock:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://app:123123123@db/app
    depends_on:
      - db

volumes:
  postgres_data:
